### ISSUE TITLE
Active Directory - Authentication

### ISSUE THREAD

**Issue by pir8g33k** [kumarvna/terraform-azurerm-app-service#4]
Hi i tried to set enable_auth_settings to true but the output on terraform plan still set to disabled, how can i enable or to set to authentication (active_directory_auth_setttings) and create the apps automatically for app registration and enterprise apps?

**Comment by kumarvna** [comment]
Hi, 
please, enable_auth_settings to true and set the active directory setting using the below values and check.  Hope this helps. 

enable_auth_settings = true
active_directory_auth_setttings = {
        client_id         = <The Client ID of this relying party application>
        client_secret     =  <The Client Secret of this relying party application.>
}

Reference: https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal
